--- 
THETA: 0.02
REF: Zea_mays.B73_RefGen_v4.dna.toplevel.fa
MINCOV: 15
MAXCOV: 100
FRAC: 0.2
PROJECT: JRIAL1
CHROM: 10
GENOTYPE_ERROR: 0.03
NE_GUESSTIMATE: 500000
FILTER_PARAMS: --minDP 15 --maxDP 100 --hwe 0.01 --maf 0.01 --minGQ 30 --minQ 30 --max-missing 0.7  --max-alleles 2 --min-alleles 2  --remove-indels
